# Generated by Django 5.2.6 on 2025-09-27 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_patientcohort_actionableinsight_treatmentoutcome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymizedPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('age_group', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], max_length=1)),
                ('race', models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black or African American'), ('ASIAN', 'Asian'), ('NATIVE', 'American Indian or Alaska Native'), ('PACIFIC', 'Native Hawaiian or Other Pacific Islander'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('ethnicity', models.CharField(choices=[('HISPANIC', 'Hispanic or Latino'), ('NON_HISPANIC', 'Not Hispanic or Latino'), ('UNKNOWN', 'Unknown')], max_length=15)),
                ('zip_code_prefix', models.CharField(max_length=3)),
                ('primary_diagnosis', models.CharField(max_length=200)),
                ('secondary_diagnoses', models.TextField(blank=True)),
                ('comorbidities', models.TextField(blank=True)),
                ('current_treatments', models.TextField(blank=True)),
                ('treatment_history', models.TextField(blank=True)),
                ('medication_adherence', models.CharField(blank=True, max_length=20)),
                ('last_lab_values', models.JSONField(blank=True, default=dict)),
                ('vital_signs', models.JSONField(blank=True, default=dict)),
                ('last_visit_date', models.DateField()),
                ('visit_frequency', models.CharField(max_length=20)),
                ('emergency_visits_6m', models.IntegerField(default=0)),
                ('hospitalizations_6m', models.IntegerField(default=0)),
                ('risk_factors', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('insurance_type', models.CharField(blank=True, max_length=50)),
                ('medication_access', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('hcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='core.hcp')),
            ],
        ),
        migrations.CreateModel(
            name='EMRDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('LAB_RESULT', 'Lab Result'), ('VITAL_SIGN', 'Vital Sign'), ('DIAGNOSIS', 'Diagnosis'), ('MEDICATION', 'Medication'), ('PROCEDURE', 'Procedure'), ('SYMPTOM', 'Symptom'), ('RISK_FACTOR', 'Risk Factor')], max_length=15)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('date_recorded', models.DateField()),
                ('is_abnormal', models.BooleanField(default=False)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='core.anonymizedpatient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(max_length=200)),
                ('outcome', models.CharField(choices=[('IMPROVED', 'Improved'), ('STABLE', 'Stable'), ('DETERIORATED', 'Deteriorated'), ('UNKNOWN', 'Unknown')], max_length=15)),
                ('outcome_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('duration_months', models.IntegerField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='core.anonymizedpatient')),
            ],
        ),
    ]
