# Generated by Django 5.2.6 on 2025-09-27 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_patientcluster_clustervisualization_clusterinsight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('indication', models.CharField(max_length=200)),
                ('success_rate', models.FloatField()),
                ('patient_count', models.IntegerField()),
                ('evidence_level', models.CharField(max_length=20)),
                ('research_support', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('dosage_recommendations', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='MEDIUM', max_length=6)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.patientcluster')),
                ('hcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_recommendations', to='core.hcp')),
            ],
        ),
        migrations.DeleteModel(
            name='ClusterVisualization',
        ),
    ]
