# Generated by Django 5.2.6 on 2025-09-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hcp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymizedpatient',
            name='zip_code_prefix',
            field=models.CharField(max_length=5),
        ),
    ]
