# Generated by Django 5.0 on 2025-09-27 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_anonymizedpatient_zip_code_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchupdate',
            options={'ordering': ['-date', '-relevance_score']},
        ),
        migrations.AddField(
            model_name='researchupdate',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchupdate',
            name='is_high_impact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researchupdate',
            name='relevance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='researchupdate',
            name='source',
            field=models.CharField(default='Manual', max_length=100),
        ),
        migrations.AddField(
            model_name='researchupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='researchupdate',
            index=models.Index(fields=['specialty', '-date'], name='core_resear_special_300970_idx'),
        ),
        migrations.AddIndex(
            model_name='researchupdate',
            index=models.Index(fields=['date'], name='core_resear_date_873496_idx'),
        ),
        migrations.AddIndex(
            model_name='researchupdate',
            index=models.Index(fields=['-relevance_score'], name='core_resear_relevan_1dc829_idx'),
        ),
    ]
