# Generated by Django 5.2.6 on 2025-09-27 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_researchupdate_options_researchupdate_abstract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_title', models.CharField(max_length=200)),
                ('recommendation_summary', models.TextField()),
                ('evidence_summary', models.TextField()),
                ('patient_data_evidence', models.JSONField()),
                ('research_evidence', models.JSONField()),
                ('cluster_evidence', models.JSONField()),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='MEDIUM', max_length=6)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='DRAFT', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('viewed_date', models.DateTimeField(blank=True, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('hcp_response', models.TextField(blank=True)),
                ('cluster_insights', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.patientcluster')),
                ('hcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligent_recommendations', to='core.hcp')),
                ('hcr_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='HCRMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('RECOMMENDATION', 'Recommendation'), ('GENERAL', 'General Message'), ('FOLLOW_UP', 'Follow-up')], default='GENERAL', max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('message_content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('recipient_hcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='core.hcp')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.intelligentrecommendation')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientIssueAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('total_patients_analyzed', models.IntegerField()),
                ('common_issues', models.JSONField()),
                ('top_diagnoses', models.JSONField()),
                ('treatment_gaps', models.JSONField()),
                ('risk_factors', models.JSONField()),
                ('analysis_summary', models.TextField()),
                ('hcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_analyses', to='core.hcp')),
            ],
            options={
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.AddField(
            model_name='intelligentrecommendation',
            name='patient_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patientissueanalysis'),
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('feedback_text', models.TextField(blank=True)),
                ('was_helpful', models.BooleanField()),
                ('will_implement', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('hcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hcp')),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.intelligentrecommendation')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField(blank=True)),
                ('journal', models.CharField(blank=True, max_length=200)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('abstract', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('specialties', models.JSONField(default=list)),
                ('conditions_mentioned', models.JSONField(default=list)),
                ('treatments_mentioned', models.JSONField(default=list)),
                ('source_url', models.URLField(blank=True)),
                ('source_database', models.CharField(default='PubMed', max_length=100)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('scraped_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-relevance_score', '-publication_date'],
                'indexes': [models.Index(fields=['-relevance_score'], name='core_scrape_relevan_3c6acb_idx'), models.Index(fields=['publication_date'], name='core_scrape_publica_6b72e1_idx')],
            },
        ),
        migrations.AddField(
            model_name='intelligentrecommendation',
            name='relevant_research',
            field=models.ManyToManyField(blank=True, to='core.scrapedresearch'),
        ),
    ]
