# Generated by Django 5.2.6 on 2025-09-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_intelligentrecommendation_hcrmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcrrecommendation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=8),
        ),
    ]
