# Generated by Django 5.0 on 2025-09-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_hcrrecommendation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchupdate',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
